// Generated by dia2code
#ifndef STATE__ANT__H
#define STATE__ANT__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Ant - 
  class Ant : public state::Insect {
    // Setters and Getters
  };

};

#endif
