// Generated by dia2code
#ifndef STATE__ANT__H
#define STATE__ANT__H

#include <vector>
#include "BrokenChain.hpp"

namespace state {
  class Insect;
  class Case;
}

#include "Insect.hpp"
#include "Case.hpp"

namespace state {

  /// class Ant - 
  class Ant : public state::Insect {
    // Operations
  public:
    Ant ();
    std::vector<std::vector<int>> Possible_Deplacement_Insect (std::vector<Insect> list_insect_placed, std::vector<Case> list_case);
    // Setters and Getters
  };

};

#endif
