// Generated by dia2code
#ifndef STATE__BEE__H
#define STATE__BEE__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Bee - 
  class Bee : public state::Insect {
    // Setters and Getters
  };

};

#endif
