// Generated by dia2code
#ifndef STATE__BEETLE__H
#define STATE__BEETLE__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Beetle - 
  class Beetle : public state::Insect {
    // Setters and Getters
  };

};

#endif
