// Generated by dia2code
#ifndef STATE__CASE__H
#define STATE__CASE__H

#include <vector>

namespace state {

  /// class Case - 
  class Case {
    // Attributes
  private:
    std::vector<int> position;
    bool empty;
    // Operations
  public:
    std::vector<int> GetPosition ();
    Case  (std::vector<int> coord, bool empty);
    bool GetEmpty ();
    void SetEmpty (bool state);
    int Get_i ();
    int Get_j ();
    // Setters and Getters
  };

};

#endif
