// Generated by dia2code
#ifndef STATE__CRICKET__H
#define STATE__CRICKET__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Cricket - 
  class Cricket : public state::Insect {
    // Setters and Getters
  };

};

#endif
