// Generated by dia2code
#ifndef STATE__GAMESTATUS__H
#define STATE__GAMESTATUS__H


namespace state {

  enum GameStatus {
    Player_A_playing,
    Player_B_playing,
    Player_A_won,
    Player_B_won,
    Player_A_lost,
    Player_B_lost,
    Player_A_waiting,
    Player_B_waiting
  };

};

#endif
