// Generated by dia2code
#ifndef STATE__GAME__H
#define STATE__GAME__H

#include <vector>

namespace state {
  class Insect;
  class Map;
  class Player;
}

#include "GameStatus.hpp"
#include "Insect.hpp"
#include "Map.hpp"
#include "Player.hpp"

namespace state {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  private:
    GameStatus state;
    int nbIteration;
    std::vector<Insect> ListeAllInsect;
    Map GameMap     = Map(0,0);
    // Operations
  public:
    bool IsBeeCircled (Player player);
    void UpdateState (GameStatus state);
    void IncrementIteration ();
    GameStatus GetState ();
    int GetIteration ();
    void SetIteration (int param);
    std::vector<Insect> GetAllInsects ();
    void AppendListInsect (Insect insect);
    Game ();
    Map GetMap ();
    // Setters and Getters
  };

};

#endif
