// Generated by dia2code
#ifndef STATE__GAME__H
#define STATE__GAME__H

#include <list>

namespace state {
  class Map;
  class Insect;
  class Player;
}

#include "Map.hpp"
#include "GameStatus.hpp"
#include "Insect.hpp"
#include "Player.hpp"

namespace state {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  public:
    Map GameMap;
  private:
    GameStatus state;
    int nbIteration;
    std::list<Insect> ListeAllInsect;
    // Operations
  public:
    bool IsBeeCircled (Player player);
    void UpdateState (GameStatus state);
    void IncrementIteration ();
    void Display_Possible_Moves (std::list<std::list<int>> ListMoves);
    GameStatus GetState ();
    int GetIteration ();
    void SetIteration (int param);
    std::list<Insect> GetAllInsects ();
    void AppendListInsect (Insect insect);
    void AddMap (Map map);
    Map GetMap ();
    Game (GameStatus state, int iteration, Map map);
    // Setters and Getters
  };

};

#endif
