// Generated by dia2code
#ifndef STATE__GRASSHOOPER__H
#define STATE__GRASSHOOPER__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Grasshooper - 
  class Grasshooper : public state::Insect {
    // Setters and Getters
  };

};

#endif
