// Generated by dia2code
#ifndef STATE__INSECT__H
#define STATE__INSECT__H

#include <string>
#include <vector>

namespace state {

  /// class Insect - 
  class Insect {
    // Attributes
  private:
    std::string Name;
    std::string Color;
    std::vector<int> Coord;
    int Level;
    // Operations
  public:
    void Select_Insect ();
    void Update_Coord (std::vector<int> coord);
    std::vector<int> Get_Position ();
    std::vector<std::vector<int>> Possible_Placement_Insect ();
    virtual std::vector<std::vector<int>> Possible_Deplacement_Insect ();
    std::string GetName ();
    std::string GetColor ();
    int GetLevel ();
    void SetPosition (std::vector<int> coord);
    void SetLevel (int level);
    Insect (std::string name, std::string color, std::vector<int> coord, int level);
    // Setters and Getters
  };

};

#endif
