// Generated by dia2code
#ifndef STATE__LADYBUG__H
#define STATE__LADYBUG__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Ladybug - 
  class Ladybug : public state::Insect {
    // Setters and Getters
  };

};

#endif
