// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <list>

namespace state {
  class Case;
}

#include "GameStatus.hpp"
#include "Case.hpp"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    // Attributes
  private:
    int Length;
    int Width;
    std::list<std::list<Case>> ListCase;
    // Operations
  public:
    Map (int length, int width);
    int GetLength ();
    int GetWidth ();
    std::list<std::list<Case>> GetListCase ();
    // Setters and Getters
  };

};

#endif
