// Generated by dia2code
#ifndef STATE__MOSQUITO__H
#define STATE__MOSQUITO__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Mosquito - 
  class Mosquito : public state::Insect {
    // Setters and Getters
  };

};

#endif
