// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <list>

namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  private:
    std::string Name;
    std::string Color;
    std::list<Insect> ListInsectRemaining;
    static std::list<Insect> ListInsectPlayed;
    // Operations
  public:
    Player (std::string name, std::string color);
    std::string GetName ();
    std::string GetColor ();
    std::list<Insect> Get_List_Insect (std::list<Insect> list);
    void Add_Insect (Insect insecte, std::list<Insect> list);
    void Remove_Insect (Insect insecte, std::list<Insect> list);
    // Setters and Getters
  };

};

#endif
