// Generated by dia2code
#ifndef STATE__SPIDER__H
#define STATE__SPIDER__H

#include <string>
#include <vector>

namespace state {
  class Insect;
  class Case;
}

#include "Insect.hpp"
#include "Case.hpp"

namespace state {

  /// class Spider - 
  class Spider : public state::Insect {
    // Operations
  public:
    Spider (std::string name, std::string color, std::vector<int> coord, int level);
    std::vector<std::vector<int>> Possible_Deplacement_Insect (std::vector<Insect> list_insect_placed, std::vector<Case> list_case);
    std::vector<std::vector<int>> first_x (std::vector<Case> list_case, int abs_to_look, int ord_to_look, Case case_premier, std::vector<std::vector<int>> list_possible_placement, int i_depart, int j_depart);
    std::vector<std::vector<int>> second_x (std::vector<Case> list_case, int abs_to_look, int ord_to_look, Case case_deuxieme, std::vector<std::vector<int>> list_possible_placement, int i_case1, int j_case1, int i_depart, int j_depart);
    std::vector<int> third_x (std::vector<Case> list_case, int abs_to_look, int ord_to_look, Case case_troisieme, std::vector<std::vector<int>> list_possible_placement, int i_case1, int j_case1, int i_depart, int j_depart);
    // Setters and Getters
  };

};

#endif
