// Generated by dia2code
#ifndef STATE__SPIDER__H
#define STATE__SPIDER__H


namespace state {
  class Insect;
}

#include "Insect.hpp"

namespace state {

  /// class Spider - 
  class Spider : public state::Insect {
    // Setters and Getters
  };

};

#endif
