services:
  plt:
    container_name: plt
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - .gitignore:/app/.gitignore
      - ./src:/app/src
      - ./extern:/app/extern
      - ./cmake:/app/cmake
      - ./CMakeFiles:/app/CMakeFiles
      - ./lib:/app/lib
      - ./test:/app/test
      - ./rapport:/app/rapport
      - /run/user/${UID}/${WAYLAND_DISPLAY}:/run/${WAYLAND_DISPLAY}
    tty: true
    environment:
      - XDG_RUNTIME_DIR=/run/user/${UID}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}

    stdin_open: true
    command: /bin/bash

