services:
  plt:
    container_name: plt
    working_dir: /app
    build:
      context: .
      ipc: host
      args:
      - USERNAME=plt
      - USER_UID= 1000 # $(id -u)
      - USER_GID= 1000 # $(id -g)
      - DISPLAY= ${DISPLAY:-}
      dockerfile: Dockerfile
    # user: $(id -u):$(id -g)
    user: $USER_UID:$USER_GID
    volumes:
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - .gitignore:/app/.gitignore
      - ./src:/app/src
      - ./extern:/app/extern
      - ./cmake:/app/cmake
      - ./CMakeFiles:/app/CMakeFiles
      - ./lib:/app/lib
      - ./test:/app/test
      - ./rapport:/app/rapport
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
    tty: true
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - GDK_BACKEND=wayland
      - QT_QPA_PLATFORM=wayland
    stdin_open: true