// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <SFML/Graphics.hpp>

namespace render {
  class MapDraw;
  class InsectDraw;
  class TextDraw;
};
namespace state {
  class Game;
}

#include "MapDraw.hpp"
#include "InsectDraw.hpp"
#include "TextDraw.hpp"
#include "state/Game.hpp"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  public:
    MapDraw mapDraw;
    InsectDraw insectDraw;
    TextDraw textDraw;
    // Operations
  public:
    Scene (state::Game state);
    void drawScene (state::Game state, sf::RenderWindow& window);
    // Setters and Getters
  };

};

#endif
