// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <vector>

namespace state {
  class Game;
};
namespace ai {
  class AI;
}

#include "AI.hpp"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Operations
  public:
    RandomAI (state::Game& game);
    std::vector<int> runAI ();
    // Setters and Getters
  };

};

#endif
