// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class Player;
};
namespace engine {
  class Engine;
}

#include "CommandTypeId.hpp"
#include "state/GameStatus.hpp"
#include "Engine.hpp"

namespace engine {

  /// class Command - 
  class Command {
    // Attributes
  protected:
    CommandTypeId commandTypeId;
    state::GameStatus playing;
    state::Player* player;
    // Operations
  public:
    Command ();
    CommandTypeId getCommandTypeId ();
    virtual bool execute ();
    // Setters and Getters
    void setCommandTypeId(CommandTypeId commandTypeId);
    state::GameStatus getPlaying() const;
    void setPlaying(state::GameStatus playing);
    const state::Player*& getPlayer() const;
    void setPlayer(const state::Player*& player);
  };

};

#endif
