// Generated by dia2code
#ifndef ENGINE__DEPLACEMENTCOMMAND__H
#define ENGINE__DEPLACEMENTCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.hpp"

namespace engine {

  /// class DeplacementCommand - 
  class DeplacementCommand : public engine::Command {
    // Setters and Getters
  };

};

#endif
