// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>

namespace state {
  class Game;
};
namespace engine {
  class Command;
}

#include "state/Game.hpp"
#include "Command.hpp"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  public:
    state::Game currentState;
    std::vector<Command> listCommands;
    // Operations
  public:
    Engine (state::Game& game);
    void init ();
    state::Game getState ();
    void addCommand (Command ptr_cmd);
    void setState (state::Game& game);
    // Setters and Getters
  };

};

#endif
