// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>

namespace state {
  class Game;
};
namespace engine {
  class Command;
};
namespace state {
  class Player;
}

#include "Command.hpp"
#include "state/Game.hpp"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  public:
    state::Game* currentGame;
    std::vector<Command> listCommands;
    // Operations
  public:
    Engine (state::Game& game);
    void init ();
    state::Game* getState ();
    void addCommand (Command ptr_cmd);
    void UpdateState (state::Game& game, int commandid, state::Insect& insect_moving, std::vector<int> pos_target, state::Player& player);
    // Setters and Getters
  };

};

#endif
