// Generated by dia2code
#ifndef ENGINE__PLACEMENTCOMMAND__H
#define ENGINE__PLACEMENTCOMMAND__H

#include <vector>

namespace state {
  class Player;
};
namespace engine {
  class Engine;
  class Command;
}

#include "state/GameStatus.hpp"
#include "CommandTypeId.hpp"
#include "Command.hpp"

namespace engine {

  /// class PlacementCommand - 
  class PlacementCommand : public engine::Command {
    // Attributes
  public:
    std::vector<int> position;
    state::Insect* insect;
    std::vector<std::vector<int>> placement_possible;
    // Operations
  public:
    PlacementCommand (state::GameStatus gamestatus, std::vector<int> position_insect, state::Insect& insect, CommandTypeId commandId, state::Player& player, std::vector<std::vector<int>> placement_possible);
    bool execute (engine::Engine& engine);
    // Setters and Getters
  };

};

#endif
