// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.hpp"
#include "engine/Command.hpp"
#include "engine/Engine.hpp"
#include "engine/PlacementCommand.hpp"
#include "engine/DeplacementCommand.hpp"
#endif
