// Generated by dia2code
#ifndef CASE__H
#define CASE__H

/// class Case - 
class Case {
  // Attributes
public:
  list<int> Coordonnee;
  bool occupee;
  // Operations
public:
  List<int> GetCoordonees ();
  void Case (list<int> coord, bool occupe);
  bool GetOccupe ();
  void SetOccupe (bool etat);
  // Setters and Getters
};

#endif
