// Generated by dia2code
#ifndef INSECT__H
#define INSECT__H

/// class Insect - 
class Insect : public Scarabe, public Abeille, public Cocinelle, public Grillon, public Araigné, public Sauterelle, public Moustique, public Fourmi {
  // Attributes
public:
  string nom;
  string couleur;
  list<int> position;
  /// Certains pions peuvent monter sur d'autres donc le niveau 0 correspond au sol et le niveau 1 est celui du dessus
  int niveau;
  // Operations
public:
  void Select_Insect ();
  void Update_Position_Insecte ();
  list<int> getpos ();
  List<List<int>> Placement_possible_Insecte ();
  virtual List<List<int>> Deplacement_possible_Insecte () = 0;
  string GetNom ();
  string GetCouleur ();
  List<int> GetPosition ();
  int GetNiveau ();
  void SetPosition (list<int> coord);
  void SetNiveau (int niveau);
  // Setters and Getters
};

#endif
