// Generated by dia2code
#ifndef JEU__H
#define JEU__H

/// class Jeu - 
class Jeu {
  // Associations
  // Attributes
public:
  GameStatus etat;
  int nbTours;
  list<Insect> ListeAllInsect;
  plateau Plateau;
  // Operations
public:
  bool IsBeeACircled ();
  bool IsBeeBCircled ();
  void UpdateEtat ();
  void IncrementeTour ();
  void Affiche_coups_possibles (List<int> ListeCoups);
  void SetEtat (GameStatus status);
  GameStatus GetEtat ();
  int GetNbTours ();
  void SetNbTours (int param);
  list<Insect> GetAllInsects ();
  void AppendListInsect (Insect insecte);
  Plateau GetPlateau ();
  // Setters and Getters
};

#endif
