// Generated by dia2code
#ifndef JOUEUR__H
#define JOUEUR__H

/// class Joueur - 
class Joueur {
  // Associations
  // Attributes
public:
  string Nom;
  string Couleur;
  list<Insect> ListeInsectRestants;
  list<Insect> ListeInsectJoues;
  // Operations
public:
  void Creation_Joueur (string Nom, string Couleur);
  string GetNom ();
  string GetCouleur ();
  list<Insect> Get_List_Insect_Restants ();
  list<Insect> Get_List_Insect_Joues ();
  void Add_Insect_Restant (Insect insecte);
  void Remove_Insect_Restant (Insect insecte);
  void Add_Insect_Joue (Insect insecte);
  // Setters and Getters
};

#endif
